#!/usr/bin/env bash
# Summary: List all Terraform versions that contain the given executable
# Usage: tfenv whence [--path] <command>

set -e
[ -n "$TFENV_DEBUG" ] && set -x

# Provide tfenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec tfenv-shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  tfenv-versions --bare | while read -r version; do
    path="$(tfenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

TFENV_COMMAND="$1"
if [ -z "$TFENV_COMMAND" ]; then
  tfenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$TFENV_COMMAND")"
[ -n "$result" ] && echo "$result"
