#!/usr/bin/env bash
# Usage: tfenv completions <command> [<args>...]

set -e
[ -n "$TFENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  tfenv-help --usage completions >&2
  exit 1
fi

# Provide tfenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec tfenv-commands
fi

COMMAND_PATH="$(type -P "tfenv-$COMMAND" "tfenv-sh-$COMMAND" | head -n1)"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide tfenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
