#!/usr/bin/env bash
# Summary: List hook scripts for a given tfenv command
# Usage: tfenv hooks <command>

set -e
[ -n "$TFENV_DEBUG" ] && set -x

# Provide tfenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

TFENV_COMMAND="$1"
if [ -z "$TFENV_COMMAND" ]; then
  tfenv-help --usage hooks >&2
  exit 1
fi

IFS=: read -r -a hook_paths <<<"$TFENV_HOOK_PATH"

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$TFENV_COMMAND"/*.bash; do
    echo "$script"
  done
done
shopt -u nullglob
